name: CI
on:
    push:
      branches:
        - master
    pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry/
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Cache Docker
        uses: actions/cache@v1
        with:
          path: /var/lib/docker/
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install httpie -y
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools
          python3 -m pip install poetry==1.0.5
          poetry config virtualenvs.create false
          poetry install
      - name: Start Services
        run: docker-compose --project-name oliver up --build --detach
      - name: Wait for Services
        run: |
          echo "Waiting for Cromwell to come up..."
          NEXT_WAIT_TIME=0
          until http HEAD http://localhost:8000 &> /dev/null || [ $NEXT_WAIT_TIME -eq 30 ]; do
            echo "Sleeping ${NEXT_WAIT_TIME} seconds..."
            sleep $(( NEXT_WAIT_TIME++ ))
          done

          echo "Waiting for httpbin to come up..."
          NEXT_WAIT_TIME=0
          until http HEAD http://localhost:80 &> /dev/null || [ $NEXT_WAIT_TIME -eq 30 ]; do
            echo "Sleeping ${NEXT_WAIT_TIME} seconds..."
            sleep $(( NEXT_WAIT_TIME++ ))
          done
      - name: Build
        run: docker image build --tag oliver .
      - name: Seed
        run: |
          docker container run \
            --rm \
            --network oliver_default \
            --mount type=bind,source=$PWD/seeds,target=/opt/oliver/seeds \
            --mount type=bind,source=$PWD/oliver,target=/opt/oliver/oliver \
            --mount type=bind,source=$PWD/tests,target=/opt/oliver/tests \
            --entrypoint "" \
            oliver:latest \
            /bin/bash -c "bash seeds/seed.sh http://cromwell:8000 seeds/wdl/hello.wdl"
      - name: Wait for Seeds
        run: |
          touch coverage.xml
          function get_successful_results() {
            echo $(docker container run \
              --rm \
              --network oliver_default \
              --mount type=bind,source=$PWD/seeds,target=/opt/oliver/seeds \
              --mount type=bind,source=$PWD/oliver,target=/opt/oliver/oliver \
              --mount type=bind,source=$PWD/tests,target=/opt/oliver/tests \
              --mount type=bind,source=$PWD/coverage.xml,target=/opt/oliver/coverage.xml \
              --entrypoint "" \
              oliver:latest \
              /bin/bash -c "http GET http://cromwell:8000/api/workflows/v1/query | jq -r '.results[] | select(.status == \"Succeeded\") | .id' | wc -l")
          }

          echo "Waiting for workflows to finish running..."
          NEXT_WAIT_TIME=0
          until [[ $(get_successful_results) -eq 5 ]] || [ $NEXT_WAIT_TIME -eq 30 ]; do
            echo "Sleeping ${NEXT_WAIT_TIME} seconds..."
            sleep $(( NEXT_WAIT_TIME++ ))
          done
      - name: Pytest
        run: |
          docker container run \
            --rm \
            --network oliver_default \
            --mount type=bind,source=$PWD/seeds,target=/opt/oliver/seeds \
            --mount type=bind,source=$PWD/oliver,target=/opt/oliver/oliver \
            --mount type=bind,source=$PWD/tests,target=/opt/oliver/tests \
            --mount type=bind,source=$PWD/coverage.xml,target=/opt/oliver/coverage.xml \
            --entrypoint "" \
            oliver:latest \
            /bin/bash -c "oliver configure --defaults && oliver config set cromwell_server http://cromwell:8000 && pytest tests --cov=./ --cov-report=xml -v"
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false
      - name: Ensure User Owns Docker Cache
        run: |
          sudo chown -R $USER /var/lib/docker