name: Lint
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry==1.0.5
          poetry install
      - run: pylint oliver
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: lgeiger/black-action@v1.0.1
        with:
          args: "oliver --check"