name: Lint
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry/
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools
          python3 -m pip install poetry==1.0.5
          poetry config virtualenvs.create false
          poetry install
      - run: pylint oliver
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: lgeiger/black-action@v1.0.1
        with:
          args: "oliver --diff"