name: Pylint
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: python setup.py install
      - run: which python
      - run: which pylint
      - run: pylint oliver