name: Integration and Unit Tests
on: 
    push:
      branches:
        - master
    pull_request:

jobs:
  tests:
    name: Integration Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install httpie -y
      - name: Start services
        run: docker-compose --project-name oliver up --build --detach
      - name: Wait for services to come available
        run: |
          echo "Waiting for Cromwell to come up..."
          NEXT_WAIT_TIME=0
          until http HEAD http://localhost:8000 &> /dev/null || [ $NEXT_WAIT_TIME -eq 30 ]; do
            echo "Sleeping ${NEXT_WAIT_TIME} seconds..."
            sleep $(( NEXT_WAIT_TIME++ ))
          done

          echo "Waiting for httpbin to come up..."
          NEXT_WAIT_TIME=0
          until http HEAD http://localhost:80 &> /dev/null || [ $NEXT_WAIT_TIME -eq 30 ]; do
            echo "Sleeping ${NEXT_WAIT_TIME} seconds..."
            sleep $(( NEXT_WAIT_TIME++ ))
          done
      - name: Build
        run: docker image build --tag oliver .
      - name: Seed
        run: |
          docker container run \
            --rm \
            --network oliver_default \
            --mount type=bind,source=$PWD/seeds,target=/opt/oliver/seeds \
            --mount type=bind,source=$PWD/oliver,target=/opt/oliver/oliver \
            --mount type=bind,source=$PWD/scripts,target=/opt/oliver/scripts \
            --mount type=bind,source=$PWD/tests,target=/opt/oliver/tests \
            --entrypoint "" \
            oliver:latest \
            /bin/bash -c "bash seeds/seed.sh http://cromwell:8000 seeds/wdl/hello.wdl"
      - name: Wait for seeds
        run: |
          touch coverage.xml
          function get_successful_results() {
            echo $(docker container run \
              --rm \
              --network oliver_default \
              --mount type=bind,source=$PWD/seeds,target=/opt/oliver/seeds \
              --mount type=bind,source=$PWD/oliver,target=/opt/oliver/oliver \
              --mount type=bind,source=$PWD/scripts,target=/opt/oliver/scripts \
              --mount type=bind,source=$PWD/tests,target=/opt/oliver/tests \
              --mount type=bind,source=$PWD/coverage.xml,target=/opt/oliver/coverage.xml \
              --entrypoint "" \
              oliver:latest \
              /bin/bash -c "http GET http://cromwell:8000/api/workflows/v1/query | jq -r '.results[] | select(.status == \"Succeeded\") | .id' | wc -l")
          }

          echo "Waiting for workflows to finish running..."
          NEXT_WAIT_TIME=0
          until [[ $(get_successful_results) -eq 5 ]] || [ $NEXT_WAIT_TIME -eq 30 ]; do
            echo "Sleeping ${NEXT_WAIT_TIME} seconds..."
            sleep $(( NEXT_WAIT_TIME++ ))
          done
      - name: Pytest
        run: |
          docker container run \
            --rm \
            --network oliver_default \
            --mount type=bind,source=$PWD/seeds,target=/opt/oliver/seeds \
            --mount type=bind,source=$PWD/oliver,target=/opt/oliver/oliver \
            --mount type=bind,source=$PWD/scripts,target=/opt/oliver/scripts \
            --mount type=bind,source=$PWD/tests,target=/opt/oliver/tests \
            --mount type=bind,source=$PWD/coverage.xml,target=/opt/oliver/coverage.xml \
            --entrypoint "" \
            oliver:latest \
            /bin/bash -c "oliver configure --defaults && oliver config set cromwell_server http://cromwell:8000 && pytest tests --cov=./ --cov-report=xml -v"
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false